Mission09_espilker/Components/CartSummaryViewComponent.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Mission09_espilker.Models;

namespace Mission09_espilker.Components
{
    public class CartSummaryViewComponent : ViewComponent
    {
        private Basket basket;
        public CartSummaryViewComponent (Basket basketService)
        {
            basket = basketService;
        }
        public IViewComponentResult Invoke()
        {
            return View(basket);
        }
    }
}

Mission09_espilker/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission09_espilker.Models;

namespace Mission09_espilker.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookCateogry"];
            var categories = repo.Books
                    .Select(x => x.Category)
                    .Distinct()
                    .OrderBy(x => x);

            return View(categories);
        }
    }
}

Mission09_espilker/Views/Shared/BookSummary.cshtml
@{
}
@model Book

    <style>

        button {

            animation-name: example;
            animation-duration: 10s;
        }

        @@keyframes example {
            from {
                background-color: midnightblue;
            }

            to {
                background-color: palegreen;
            }
        }
    </style>

    <div class="card card-outline-primary m-1 p-1">
        <div class="bg-light p-1">
            <h4>@Model.Title</h4>

            <span class="badge bg-info" style="float:right; color:white">
                Category: @Model.Category
            </span>
        </div>
        <ul>
            <li>Author: @Model.Author</li>
            <li>Publisher: @Model.Publisher</li>
            <li>ISBN: @Model.Isbn</li>
            <li>Classification: @Model.Classification</li>
            <li>Pages: @Model.PageCount</li>
            <li>Price: @Model.Price</li>
        </ul>

        <form method="post" asp-page="/shopping">
            <input type="hidden" asp-for="@Model.BookId" />
            <input type="hidden" name="returnUrl" value="@ViewContext.HttpContext.Request.PathAndQuery()" />
            <span class="card-text">
                <button type="submit" class="btn btn-success btn-group-sm float-end">Add to Cart</button>
            </span>
        </form>
    </div>

Mission09_espilker/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission09_espilker</title>

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>

    <div class="bg-dark text-white p-2">
        <div class="container-fluid">
            <div class="row">
                <div class="col navbar-brand">Book Store</div>
                <div class="col-6 text-right">
                    <vc:cart-summary />
                </div>
            </div>
        </div>
    </div>


    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:category></vc:category>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>

</body>
</html>