Mission09_espilker/Components/CategoryViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Mission09_espilker.Models;

namespace Mission09_espilker.Components
{
    public class CategoryViewComponent : ViewComponent
    {
        private IBookstoreRepository repo { get; set; }

        public CategoryViewComponent (IBookstoreRepository temp)
        {
            repo = temp;
        }
        public IViewComponentResult Invoke()
        {
            ViewBag.SelectedType = RouteData?.Values["bookCateogry"];
            var categories = repo.Books
                    .Select(x => x.Category)
                    .Distinct()
                    .OrderBy(x => x);

            return View(categories);
        }
    }
}

Mission09_espilker/Controllers/CheckoutController.cs
using Microsoft.AspNetCore.Mvc;
using Mission09_espilker.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Mission09_espilker.Controllers
{
    public class CheckoutController : Controller
    {
        private ICheckoutRepository repo { get; set; }
        private Basket basket { get; set; }
        public CheckoutController (ICheckoutRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        [HttpGet]
        public IActionResult CheckoutPage()
        {
            return View(new Checkout());
        }

        [HttpPost]
        public IActionResult CheckoutPage(Checkout checkout)
        {
            if (basket.Items.Count() == 0)
            {
                ModelState.AddModelError("", "Sorry, your basket is empty!");
            }
            if (ModelState.IsValid)
            {
                checkout.LInes = basket.Items.ToArray();
                repo.SaveCheckout(checkout);
                basket.ClearBasket();

                return RedirectToPage("/Complete");
            }
            else { return View();  }
        }
    }
}

Mission09_espilker/Pages/Complete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Mission09_espilker.Pages
{
    public class CompleteModel : PageModel
    {
        public void OnGet()
        {
        }
    }
}

Mission09_espilker/Pages/Shopping.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Mission09_espilker.Infrastructure;
using Mission09_espilker.Models;

namespace Mission09_espilker.Pages
{
    public class ShoppingModel : PageModel
    {
        private IBookstoreRepository repo { get; set; }
        public Basket basket { get; set; }
        public string ReturnUrl { get; set; }
        public ShoppingModel (IBookstoreRepository temp, Basket b)
        {
            repo = temp;
            basket = b;
        }

        public void OnGet(string returnUrl)
        {
            ReturnUrl = returnUrl ?? "/";
        }

        public IActionResult OnPost(int bookId, string returnUrl)
        {
            Book b = repo.Books.FirstOrDefault(x => x.BookId == bookId);

            basket.AddItem(b, 1);

            return RedirectToPage(new { ReturnUrl = returnUrl });
        }

        public IActionResult OnPostRemove (int bookId, string returnUrl)
        {
            basket.RemoveItem(basket.Items.First(x => x.Book.BookId == bookId).Book);
            return RedirectToPage(new {ReturnUrl = returnUrl});
        }
    }
}

Mission09_espilker/Pages/Complete.cshtml
@page
@model Mission09_espilker.Pages.CompleteModel
@{
}

<div class="text-center"
     <h2>Your order is complete</h2>
<a class="btn btn-primary" asp-controller="Home">Home</a>
    </div>

Mission09_espilker/Pages/Shopping.cshtml
@page
@model Mission09_espilker.Pages.ShoppingModel
@{
}


<h2>Your Cart</h2>
<style>

    a {

        animation-name: example;
        animation-duration: 10s;
    }

    img {
        width: 100px;
        height: 100px;
        position: relative;
       
        animation-name: move;
        animation-duration: 4s;
    }

    @@keyframes example {
        from {
            background-color: midnightblue;
        }

        to {
            background-color: palegreen;
        }
    }

    @@keyframes move {
        0% {
            left: 0px;
            top: 0px;
        }

        25% {
            left: 200px;
            top: 0px;
        }

        50% {
            left: 200px;
            top: 200px;
        }

        75% {
            left: 0px;
            top: 200px;
        }

        100% {
            left: 0px;
            top: 0px;
        }
    }
</style>


<table class="table table-bordered table-striped">
    <thead>
        <tr>
            <th>Book</th>
            <th>Quantity</th>
            <th>Price</th>
            <th>Subtotal</th>
        </tr>
    </thead>

    <tbody>
        @foreach (var i in Model.basket.Items)
        {
            <tr>
                <td>@i.Book.Title</td>
                <td>@i.Quantity</td>
                <td>@i.Book.Price</td>
                <td>@((i.Quantity * i.Book.Price).ToString("c"))</td>

                <td class="text-center">
                    <form method="post" asp-page-handler="Remove">
                        <input type="hidden" name="bookId" value="@i.Book.BookId" />
                        <input type="hidden" name="returnUrl" value="@Model.ReturnUrl" />
                        <button type="submit" class="btn btn-sm btn-danger">Remove</button>
                    
                    </form>
                </td>
            </tr>
        }
    </tbody>

    <tfoot>
        <tr>
            <td colspan="3">Total:</td>
            <td>@Model.basket.CalculateTotal().ToString("c")</td>
        </tr>
    </tfoot>
</table>

<div>
    <a class="btn btn-primary" style="background-color:palegreen" href="@Model.ReturnUrl">Continue Shopping</a>
    <a class="btn btn-primary" style="background-color:palegreen" asp-controller="Checkout" asp-action="CheckoutPage" >Checkout</a>
</div>


<br />
<img src="~/img/cart.png" width="20" height="20" />

Mission09_espilker/Pages/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Mission09_espilker</title>

    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />*@
    <link href="/lib/twitter-bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    @*<link rel="stylesheet" href="~/css/site.css" />*@
</head>
<body>
    <div class="bg-dark text-white p-2">
        <span class="navbar-brand ml-2">Book Store</span>
    </div>

    <div class="row m-1 p-1">
        <div id="types" class="col-3">
            <vc:category></vc:category>
        </div>

        <div class="col-9">
            @RenderBody()
        </div>
    </div>

</body>
</html>